# Generated by Django 3.2.8 on 2022-03-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_doctor', '0002_auto_20220315_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
    ]
