# Generated by Django 3.2.8 on 2022-05-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_doctor', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='year_of_starting_work',
            new_name='graduation_year',
        ),
    ]
