# Generated by Django 3.2.8 on 2022-04-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
