# Generated by Django 3.2.8 on 2022-04-13 16:55
from django.contrib.auth.hashers import make_password
from django.db import migrations

import json
from dotenv import load_dotenv
import os

from api_account.constants import RoleData

load_dotenv()


def initial_data(apps, schema_editor):
    account_model = apps.get_model("api_account", 'Account')
    user_model = apps.get_model("api_user", 'User')
    insurance_model = apps.get_model("api_user", "Insurance")

    json_data = json.load(open('api_user/constants/user.json', encoding="utf8"))
    default_user_password = make_password(os.getenv('DEFAULT_CUSTOMER_PASSWORD'))
    user_role = RoleData.USER.value.get("id")

    users = []

    for user_data in json_data:
        account_data = user_data['account']
        account = account_model(username=account_data['username'],
                                email=account_data['email'],
                                password=default_user_password,
                                role_id=user_role)
        account.save()
        user_data['account'] = account

        insurance_data = user_data['insurance']
        insurance = insurance_model(**insurance_data)
        insurance.save()
        user_data['insurance'] = insurance
        users.append(user_model(**user_data))

    user_model.objects.bulk_create(users)


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_alter_user_career'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
