# Generated by Django 3.2.8 on 2021-12-19 15:46
from django.contrib.auth.hashers import make_password
from django.db import migrations
from dotenv import load_dotenv
import os

from api_account.constants import RoleData

load_dotenv()


def initial_admin_data(apps, schema_editor):
    account_model = apps.get_model("api_account", "Account")

    admin = account_model(username="admin",
                          email="huyviet2582000@gmail.com",
                          password=make_password(os.getenv('DEFAULT_ADMIN_PASSWORD')),
                          role_id=RoleData.ADMIN.value.get('id'))

    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0002_migrate_roles'),
    ]

    operations = [
        migrations.RunPython(initial_admin_data, migrations.RunPython.noop)
    ]
