# Generated by Django 3.2.8 on 2022-06-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0003_migrate_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
    ]
